name: closet_client
description: ClosetMate CLI 클라이언트 애플리케이션
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.2.0
  firebase_auth: ^6.1.0
  http: ^1.6.0
  http_parser: ^4.0.2
  google_fonts: ^6.1.0
  image_picker: ^1.2.1
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^6.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/
  
  fonts:
    - family: GmarketSans
      fonts:
        - asset: assets/font/GmarketSansTTFMedium.ttf
          weight: 500
    - family: MaterialSymbolsRounded
      fonts:
        - asset: assets/font/MaterialSymbolsRounded[FILL,GRAD,opsz,wght].ttf
    - family: MaterialSymbolsOutlined
      fonts:
        - asset: assets/font/MaterialSymbolsOutlined[FILL,GRAD,opsz,wght].ttf
    - family: MaterialSymbolsSharp
      fonts:
        - asset: assets/font/MaterialSymbolsSharp[FILL,GRAD,opsz,wght].ttf

