name: closet_client
description: ClosetMate CLI 클라이언트 애플리케이션
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.1.0
  http_parser: ^4.0.2

dev_dependencies:
  lints: ^3.0.0

